name: Bug Report
description: Create a report describing unexpected or incorrect behavior in this package
labels: [Bug]
body:
  - type: markdown
    attributes:
      value: |
        We know opening issues takes effort, and we appreciate your time.

        Please be aware that everyone has to follow our code of conduct:
        https://sunpy.org/coc

        Please have a search on our GitHub repository to see if a similar issue has already been posted.
        If a similar issue is closed, have a quick look to see if you are satisfied by the resolution.
        If not please go ahead and open a new issue!
  - type: textarea
    id: description
    attributes:
      label: Describe the bug
      description: A clear and concise description of what the bug is.
      placeholder: Enter your description here.
    validations:
      required: true
  - type: textarea
    id: reproduction-steps
    attributes:
      label: To Reproduce
      description: |
        Please include code that reproduces the issue whenever possible.
        The best reproductions are self-contained scripts with minimal dependencies.
      placeholder: |
        import sunpy

        sunpy.map.Map(...)
        etc
      value: |
        import sunpy

        sunpy.map.Map(...)
        etc
  - type: textarea
    id: behaviour
    attributes:
      label: What happened?
      description: |
        A clear and concise description of what actually happened.
        If possible, please include the relevant log output.
  - type: textarea
    id: expected-behaviour
    attributes:
      label: Expected behavior
      description: A clear and concise description of what you expected to happen.
  - type: textarea
    id: screenshots
    attributes:
      label: Screenshots
      description: If applicable, add screenshots to help explain your problem.
      placeholder: Upload your screenshots here. You can click and drag them or click on "Attach files".
  - type: textarea
    id: system-details
    attributes:
      label: System Details
      description: |
        We need to know the the package version you are using.
        Running ``import sunpy; sunpy.util.system_info()`` will print this information
      placeholder: |
        - sunpy Version:
        - astropy Version:
        - Python Version:
        - OS information:
  - type: dropdown
    id: install-method
    attributes:
      description: How did you install the package?
      label: Installation method
      multiple: true
      options:
        - pip
        - conda
        - Linux package manager
        - from source (.tar.gz)
        - git checkout
