blank_issues_enabled: false
contact_links:
  - name: SunPy Community Chat
    url: https://app.element.io/#/room/#sunpy:openastronomy.org
    about: If you want to chat with maintainers or other users.
  - name: Question/Support/Other
    url: https://community.openastronomy.org/c/sunpy/5
    about: If you have a question, problem or anything else.
