blank_issues_enabled: false
contact_links:
  - name: Sunpy Community Chat
    url: https://openastronomy.element.io/#/room/#sunpy:openastronomy.org
    about: If you want to talk to developers or users.
  - name: Question/Support/Other
    url: https://community.openastronomy.org/c/ask-questions/15
    about: If you have a usage question or problem.
