name: New Example for the Gallery
description: Adding a new example to the gallery.
labels: []
body:
  - type: markdown
    attributes:
      value: |
        We know opening issues takes effort, and we appreciate your time.
        Thank you.

        Please be aware that everyone has to follow our code of conduct:
        https://sunpy.org/coc

        Please have a search on our GitHub repository to see if a similar issue has already been posted.
        If a similar issue is closed, have a quick look to see if you are satisfied by the resolution.
        If not please go ahead and open a new issue!
  - type: textarea
    id: description
    attributes:
      label: Provide a simple description of the example
      placeholder: Provide a simple description of the example.
    validations:
      required: true
  - type: textarea
    id: topics
    attributes:
      label: Provide the topic areas that this example covers.
      placeholder: e.g., Acquiring Data, Maps, TimeSeries, etc.
    validations:
      required: true
  - type: textarea
    id: users
    attributes:
      label: Is it for beginners or advanced users?
      placeholder: Is it for beginners or advanced users?
    validations:
      required: true
  - type: textarea
    id: sample-data
    attributes:
      label: Requires NEW sample data?
      placeholder: Requires NEW sample data? If so, please provide a link to the data.
    validations:
      required: true
  - type: textarea
    id: reasons
    attributes:
      label: Reason you think it should be added to the example gallery
      placeholder: Reason you think it should be added to the example gallery.
    validations:
      required: true
